trigger:
- main
pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .Net'
  inputs:
    packageType: sdk
    version:  '6.x'